version = 0.1
default-task = 'build'

[env]
RED = "\\033[0;31m"
NC = "\\033[0m"
GRN = "\\033[0;32m"
BLUE = "\\033[0;34m"
CHECK = "printf \"${GRN}OK${NC} \" || printf \"${RED}FAIL${NC} \""
BIN = "./execute.rb"
PP = "../deno/build/preprocess"

[[task]]
name = 'build-deno-preprocess'
run = 'chomp -c ../deno/ build'

[[task]]
name = 'ruby-interpret'
run = '''
	cat ../ff/example.ff | ${{BIN}} | cmp --s - "../ff/example.out"
'''

[[task]]
name = 'test'
serial = true
display = 'none'
deps = [':ruby-interpret', ':ruby-ff']

[[task]]
name = 'ruby-ff'
deps = ['../ff/##.out', '../deno/build/preprocess']
serial = true
display = 'status-only'
validation = "none"
invalidation = "always"
run = '''
  if [ -f ${DEP%.*}.ffp ]; then
    ${{PP}} ${DEP%.*}.ffp | ${{BIN}} | cmp - $DEP -s && ${{CHECK}};
  fi
  if [ -f ${DEP%.*}.ff ]; then
    cat ${DEP%.*}.ff | ${{BIN}} | cmp - $DEP -s && ${{CHECK}};
  fi
'''

