version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[env]
RED = '\033[0;31m'
GRN = '\033[0;32m'
BLUE = '\033[0;34m'
CHECK = 'printf "  ${GRN}OK${NC} " || printf "  ${RED}FAIL${NC} "'
BIN = './execute.rb'
NC = '\033[0m'

[[task]]
name = 'interpret'
run = 'cat ../ff/example.ff | ${{BIN}}'
template = 'cmp'
[task.template-options]
cmp = '../ff/example.out'

[[task]]
name = 'test'
deps = [
    ':interpret',
    ':ff',
    ':test:tap'
]
serial = true
display = 'none'

[[task]]
name = 'test:tap'
serial = true
invalidation = 'always'
validation = 'none'
run = '''
  shopt -s nullglob
  shopt -s extglob
  shopt -s globstar
  prove --exec '../shell/ff-run.sh --quiet --run ruby' ../ff/**/*.test.ffp
'''

[[task]]
name = 'ff'
deps = [
    '../ff/##.out',
]
serial = true
invalidation = 'always'
validation = 'none'
display = 'status-only'
run = '''
  if [ -f ${DEP%.*}.ffp ]; then
    ../shell/ff-run.sh --quiet --run ruby ${DEP%.*}.ffp | diff --ignore-trailing-space -q - > /dev/null 2>&1 $DEP && ${{CHECK}};
  fi
  if [ -f ${DEP%.*}.ff ]; then
    cat ${DEP%.*}.ff | ${{BIN}} | diff --ignore-trailing-space -q - > /dev/null 2>&1 $DEP && ${{CHECK}};
  fi
'''
