#!/usr/bin/env python3
"""
Regenerate ff/golf/SCORECARD.md with source stroke counts and optimized bytecode size.

Run from the repository root:

    python3 ff/golf/score_golf.py

Requires Deno on PATH (or via `mise exec --`). Uses the TypeScript compiler with
`--opt`, same pipeline as `deno/bin/ff-compile.ts --opt`.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
GOLF_DIR = Path(__file__).resolve().parent
FF_COMPILE = REPO_ROOT / "deno" / "bin" / "ff-compile.ts"


def _deno_compile_optimized(source_path: Path) -> bytes:
    """Return full .ffb bytes: ASCII header + base64 body (Deno ff-compile --opt)."""
    cmd = [
        "mise",
        "exec",
        "--",
        "deno",
        "run",
        "--no-check",
        "--allow-read",
        str(FF_COMPILE),
        "--opt",
        str(source_path),
    ]
    proc = subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        err = proc.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(
            f"compile failed for {source_path.relative_to(REPO_ROOT)} (exit {proc.returncode}): {err}"
        )
    return proc.stdout


def main() -> int:
    if not REPO_ROOT.joinpath("deno", "deno.json").is_file():
        print("Run this script from the f-flat-minor repository (deno/ not found).", file=sys.stderr)
        return 1
    if not FF_COMPILE.is_file():
        print(f"Missing {FF_COMPILE}", file=sys.stderr)
        return 1

    sources = sorted(
        list(GOLF_DIR.glob("*.ff")) + list(GOLF_DIR.glob("*.ffp")),
        key=lambda p: p.name,
    )
    rows: list[tuple[str, int, int, int]] = []

    for path in sources:
        raw = path.read_bytes()
        text = raw.decode("utf-8")
        src_bytes = len(raw)
        src_chars = len(text)
        out = _deno_compile_optimized(path)
        ffb_bytes = len(out)
        rows.append((path.name, src_bytes, src_chars, ffb_bytes))

    lines = [
        "<!-- AUTO-GENERATED by `python3 ff/golf/score_golf.py` — do not edit by hand -->",
        "",
        "| file | source bytes (UTF-8) | source chars (code points) | optimized .ffb bytes |",
        "| --- | ---: | ---: | ---: |",
    ]
    for name, sb, sc, fb in rows:
        lines.append(f"| `{name}` | {sb} | {sc} | {fb} |")

    lines.extend(
        [
            "",
            "The **optimized .ffb bytes** column is the length of stdout from",
            "`mise exec -- deno run --no-check --allow-read deno/bin/ff-compile.ts --opt <file>`:",
            "the `FbAbbCb` header plus the base64-encoded bytecode (same format as `.ffb` files).",
        ]
    )

    scorecard = GOLF_DIR / "SCORECARD.md"
    scorecard.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {scorecard.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
