#!/usr/bin/env python3
"""
Regenerate ff/golf/SCORECARD.md with source stroke counts and optimized bytecode size.

Run from the repository root:

    python3 ff/golf/score_golf.py

Requires `mise` and Deno (via the repo shell helpers). Bytecode size uses
`shell/ff-compile.sh`, which runs `deno/bin/ff-compile.ts --opt` (with
`shell/ff-preprocess.sh` for `.ffp` files).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
GOLF_DIR = Path(__file__).resolve().parent
FF_COMPILE_SH = REPO_ROOT / "shell" / "ff-compile.sh"


def _compile_optimized(source_path: Path) -> bytes:
    """Return full .ffb bytes: ASCII header + base64 body (shell/ff-compile.sh)."""
    rel = source_path.relative_to(REPO_ROOT)
    env = {**os.environ, "FF_SHELL_TRACE": "0"}
    proc = subprocess.run(
        ["/bin/bash", str(FF_COMPILE_SH), str(rel)],
        cwd=REPO_ROOT,
        capture_output=True,
        check=False,
        env=env,
    )
    if proc.returncode != 0:
        err = proc.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(
            f"compile failed for {rel} (exit {proc.returncode}): {err}"
        )
    return proc.stdout


def main() -> int:
    if not FF_COMPILE_SH.is_file():
        print(f"Missing {FF_COMPILE_SH}", file=sys.stderr)
        return 1

    sources = sorted(
        list(GOLF_DIR.glob("*.ff")) + list(GOLF_DIR.glob("*.ffp")),
        key=lambda p: p.name,
    )
    rows: list[tuple[str, int, int, int]] = []

    for path in sources:
        raw = path.read_bytes()
        text = raw.decode("utf-8")
        src_bytes = len(raw)
        src_chars = len(text)
        out = _compile_optimized(path)
        ffb_bytes = len(out)
        rows.append((path.name, src_bytes, src_chars, ffb_bytes))

    lines = [
        "<!-- AUTO-GENERATED by `python3 ff/golf/score_golf.py` — do not edit by hand -->",
        "",
        "| file | source bytes (UTF-8) | source chars (code points) | optimized .ffb bytes |",
        "| --- | ---: | ---: | ---: |",
    ]
    for name, sb, sc, fb in rows:
        lines.append(f"| `{name}` | {sb} | {sc} | {fb} |")

    lines.extend(
        [
            "",
            "The **optimized .ffb bytes** column is the length of stdout from",
            "`FF_SHELL_TRACE=0 ./shell/ff-compile.sh <file>` (repo root):",
            "the `FbAbbCb` header plus the base64-encoded bytecode (same format as `.ffb` files).",
            "`.ffp` sources are preprocessed via `shell/ff-preprocess.sh` (default `--pp bun`).",
        ]
    )

    scorecard = GOLF_DIR / "SCORECARD.md"
    scorecard.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {scorecard.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
