version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[[task]]
name = 'asbuild:#'
targets = ['./build/#.wasm', './build/#.wat']
deps = ['##.ts', './src/*.ts']
run = '''
  rm -f ./build/$MATCH.wasm
  asc $DEP --target debug --outFile ./build/$MATCH.wasm --textFile ./build/$MATCH.wat --bindings raw
'''

[[task]]
name = 'asbuild-wasi:#'
targets = ['./build/#.wasm', './build/#.wat']
deps = ['##.ts', './src/*.ts']
run = '''
  rm -f ./build/$MATCH.wasm
  asc $DEP --target debug --outFile ./build/$MATCH.wasm --textFile ./build/$MATCH.wat --bindings raw --config ./asconfig-wasi.json
'''

[[task]]
name = 'asbuild-release:#'
targets = ['./build/#-release.wasm', './build/#-release.wat']
deps = ['##.ts', './src/*.ts']
run = '''
  rm -f ./build/$MATCH-release.wasm
  asc $DEP --target release --outFile ./build/$MATCH-release.wasm --textFile ./build/$MATCH-release.wat
'''

[[task]]
name = 'asbuild-release-wasi:#'
targets = ['./build/#-release.wasm', './build/#-release.wat']
deps = ['##.ts', './src/*.ts']
run = '''
  rm -f ./build/$MATCH-release.wasm
  asc $DEP --target release --outFile ./build/$MATCH-release.wasm --textFile ./build/$MATCH-release.wat --config ./asconfig-wasi.json
'''

[[task]]
name = 'run:#'
deps = ['##.ts']
run = '''
  chomp asbuild-wasi:$MATCH
  wasmtime ./build/$MATCH.wasm
'''

[[task]]
name = 'run-release:#'
deps = ['##.ts']
run = '''
  chomp asbuild-release-wasi:$MATCH
  wasmtime ./build/$MATCH-release.wasm
'''

[[task]]
name = 'example'
deps = [':run:src/example-interp']

[[task]]
name = 'test'
serial = true
deps = [':tap', ':bats', ':interpret']

[[task]]
name = 'tap'
deps = [':asbuild:src/mp-exports', ':asbuild-wasi:src/plugin', './tests/*.js']
invalidation = 'always'
run = '''
  tap --node-arg="--no-warnings" --allow-empty-coverage --disable-coverage run ./tests/*.js
'''

[[task]]
name = 'build-bats'
deps = ['./bats/##.ts']
invalidation = 'always'
run = '''
  chomp :asbuild-wasi:bats/$MATCH
'''

[[task]]
name = 'bats'
deps = ['./bats/*.bats', ':build-bats']
invalidation = 'always'
run = '''
  bats ./bats/tests.bats
'''

[[task]]
name = 'bench:#'
deps = ['##.ts']
run = '''
  chomp asbuild-release-wasi:$MATCH
  hyperfine --warmup 10 'wasmtime ./build/$MATCH-release.wasm'
'''

[[task]]
name = 'clean'
run = '''
  rm -rf ./build
'''

[[task]]
name = 'interpret'
deps = [':asbuild-wasi:src/plugin']
run = 'cat ../ff/example.ff | node --no-warnings ./js/run.js'
template = 'cmp'
[task.template-options]
cmp = '../ff/example.out'

[[task]]
name = 'repl'
deps = [':asbuild-release-wasi:src/repl']
run = '''
  wasmer .
'''

[[task]]
name = 'build-cli'
deps = [':asbuild-release-wasi:./src/repl']
run = '''
sh ./hermit.com -f Hermitfile -o ./build/cli.com
chmod +x ./build/cli.com
'''

[[task]]
name = 'pp:#'
deps = ['##', ':asbuild-wasi:src/repl']
serial = true
invalidation = 'always'
validation = 'none'
run = '''
  ../deno/bin/ff compile $MATCH --opt --disassemble | wasmtime ./build/src/repl.wasm --silent
'''