version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[[task]]
name = 'asbuild:#'
targets = ['./build/#.wasm', './build/#.wat']
deps = ['##.ts', './assembly/*.ts']
run = '''
  rm -f ./build/$MATCH.wasm
  asc $DEP --target debug --outFile ./build/$MATCH.wasm --textFile ./build/$MATCH.wat --bindings raw
'''

[[task]]
name = 'asbuild-release:#'
targets = ['./build/#-release.wasm', './build/#-release.wat']
deps = ['##.ts', './assembly/*.ts']
run = '''
  rm -f ./build/$MATCH-release.wasm
  asc $DEP --target release --outFile ./build/$MATCH-release.wasm --textFile ./build/$MATCH-release.wat
'''

[[task]]
name = 'run:#'
deps = ['##.ts']
run = '''
  chomp asbuild:$MATCH
  wasmtime ./build/$MATCH.wasm
'''

[[task]]
name = 'run-release:#'
deps = ['##.ts']
run = '''
  chomp asbuild-release:$MATCH
  wasmtime ./build/$MATCH-release.wasm
'''

[[task]]
name = 'example'
deps = [':run:assembly/example-interp']

[[task]]
name = 'test'
serial = true
deps = [':tap', ':interpret']

[[task]]
name = 'tap'
deps = [':asbuild:assembly/plugin', './tests/*.js']
invalidation = 'always'
run = '''
  tap --node-arg="--no-warnings" --allow-empty-coverage --disable-coverage run ./tests/*.js
'''

[[task]]
name = 'as-pect'
invalidation = 'always'
run = '''
  asp
'''

[[task]]
name = 'bench:#'
deps = ['##.ts']
run = '''
  chomp asbuild-release:$MATCH
  hyperfine --warmup 10 'wasmtime ./build/$MATCH-release.wasm'
'''

[[task]]
name = 'clean'
run = '''
  rm -rf ./build
'''

[[task]]
name = 'interpret'
deps = [':asbuild:assembly/plugin']
run = 'cat ../ff/example.ff | node --no-warnings ./js/run.js'
template = 'cmp'
[task.template-options]
cmp = '../ff/example.out'

[[task]]
name = 'repl'
deps = [':asbuild-release:assembly/repl']
run = '''
  wasmer .
'''

[[task]]
name = 'build-cli'
deps = [':asbuild-release:./assembly/repl']
run = '''
sh ./hermit.com -f Hermitfile -o ./build/cli.com
chmod +x ./build/cli.com
'''

[[task]]
name = 'pp:#'
deps = ['##', ':asbuild:assembly/repl']
serial = true
invalidation = 'always'
validation = 'none'
run = '''
  ../deno/bin/ff compile $MATCH --opt --disassemble | wasmtime ./build/assembly/repl.wasm --silent
'''