version = 0.1
default-task = 'build'

[[task]]
name = 'build'
deps = ['build:src/mp']

[[task]]
name = 'build:#'
targets = ['./build/#.wasm', './build/#.wat']
deps = ['##.ts', './src/**/*.ts']
run = '''
  asc $DEP --target $MATCH --bindings --exportRuntime --optimize --outFile ./build/$MATCH.wasm --textFile ./build/$MATCH.wat
'''

[[task]]
name = 'run:#'
deps = ['##.ts']
run = '''
  chomp build:$MATCH
  wasmtime ./build/$MATCH.wasm
'''

[[task]]
name = 'example'
deps = [':run:src/interp-mp']

[[task]]
name = 'test'
invalidation = 'always'
deps = [':build:./src/test-exports']
run = '''
  tap --node-arg="--require=suppress-experimental-warnings" --allow-empty-coverage run ./tests/*.js
  bats ./bats/tests.bats
'''

[[task]]
name = 'clean'
run = '''
  rm -rf ./build
'''
