version = 0.1
default-task = 'build'

[[task]]
name = 'build'
deps = ['build:index']

[[task]]
name = 'build:#'
targets = ['./build/#.wasm', './build/#.wat']
deps = ['##.ts']
run = '''
  asc $DEP --target $MATCH --optimize --outFile ./build/$MATCH.wasm --textFile ./build/$MATCH.wat
'''

[[task]]
name = 'run:#'
deps = ['##.ts']
run = '''
  chomp build:$MATCH
  wasmtime ./build/$MATCH.wasm
'''

[[task]]
name = 'example'
deps = [':run:src/interp']

[[task]]
name = 'clean'
run = '''
  rm -rf ./build
'''
