version = 0.1
default-task = 'build:'

[[task]]
name = 'build:#'
dep = '#/chompfile.toml'
display = 'none'
validation = 'none'
run = 'chomp -c $DEP build'

[[task]]
name = 'build'
deps = [
    ':build:deno',
    ':build:bun',
    ':build:dart'
]
serial = true
display = 'none'

[[task]]
name = 'test:#'
dep = '#/chompfile.toml'
serial = true
display = 'none'
run = '''
  echo "Running ${DEP} tests..."
  chomp -c $DEP test
  echo ""
  echo ""
'''

[[task]]
name = 'test'
deps = [
    ':test:deno',
    # ':test:go',
    # ':test:cpp',
    # ':test:racket',
    # ':test:rust',
    ':test:bun',
    ':test:dart',
    ':test:node',
    ':test:python',
    ':test:ruby',
    # ':test:ghc',
    # ':test:assemblyscript',
]
serial = true
display = 'none'

[[task]]
name = 'clean:#'
dep = '#/chompfile.toml'
validation = 'none'
run = 'chomp -c $DEP clean'

[[task]]
name = 'clean'
deps = ['clean:']
validation = 'none'
run = 'rm -rf build'

[[task]]
name = 'interpret:#'
dep = '#/chompfile.toml'
validation = 'none'
serial = true
run = '''
  chomp -c $DEP interpret
  echo ""
  echo ""
'''

[[task]]
name = 'execute:#'
dep = '#/chompfile.toml'
validation = 'none'
serial = true
run = '''
  chomp -c $DEP execute
  echo ""
  echo ""
'''

[[task]]
name = 'bench'
deps = ['build:ghc', 'build:deno', 'build:go', 'build:cpp', 'build:dart', 'build:racket', 'build:rust', 'build:bun', 'build:node']
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3\
    --export-markdown benchmarks.md\
    --sort mean-time\
    './cpp/build/fact' -n watermark\
    './go/build/execute --in ./ff/example.ffb' -n go\
    './cpp/build/run ./ff/example.ff' -n cpp\
    './rust/build/example0' -n rust\
    './bun/build/ff-run ./ff/example.ff' -n bun\
    './node/build/ff-run ./ff/example.ff' -n node\
    'cat ./ff/example_v0.ff | ./dart/bin/dart.exe' -n dart\
    'cat ./ff/example.ff | ./python/execute.py' -n python\
    './deno/build/ff-execute ./ff/example.ffb' -n deno\
    'cat ./ff/example.ff | ./ruby/execute.rb' -n ruby\
    './racket/build/example' -n racket\
    './ghc/build/ff' -n ghc\
    'cd assemblyscript && cat ../ff/example.ff | node --no-warnings ./js/run.js' -n assemblyscript
'''
# './wolfram/example.wls' -n wolfram\

[[task]]
name = 'bench:execute'
deps = ['build:deno', 'build:go', 'build:cpp', 'build:racket']
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3 -N\
    './cpp/build/fact'\
    './deno/build/execute ./ff/example.ffb'\
    './go/build/execute --in ./ff/example.ffb'\
    './racket/main.rkt ./ff/example.ffb'
'''

[[task]]
name = 'bench:interp'
deps = ['build:node', 'build:bun', 'build:deno']
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3 -N \
    './deno/build/ff-run ./ff/example.ff'\
    './bun/build/ff-run ./ff/example.ff'\
    './node/build/ff-run ./ff/example.ff'
'''

[[task]]
name = 'bench:run'
deps = [':bench:run:compiled', ':bench:run:source']
validation = 'none'
serial = true
display = 'none'

[[task]]
name = 'bench:run:compiled'
deps = ['build:deno', 'build:go', 'build:cpp', 'build:rust', 'build:bun', 'build:dart']
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3 \
    './deno/build/ff-run ./ff/example.ff' -n deno\
    './go/build/run --in ./ff/example.ff' -n go\
    './cpp/build/run ./ff/example.ff' -n cpp\
    './bun/build/ff-run ./ff/example.ff' -n bun\
    './rust/build/example0' -n rust\
    'cat ./ff/example_v0.ff | ./dart/bin/dart.exe' -n dart
'''

[[task]]
name = 'bench:run:source'
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3 \
    'deno run --no-check --allow-read --allow-env ./deno/bin/ff-run.ts ./ff/example.ff'\
    'bun run ./bun/bin/ff-run.ts ./ff/example.ff'\
    'node ./node/bin/ff-run.ts ./ff/example.ff'\
    'cat ./ff/example.ff | ./python/execute.py'\
    'cat ./ff/example.ff | ./ruby/execute.rb'\
    'racket ./racket/main.rkt ./ff/example.ff'
'''

[[task]]
name = 'bench:compile'
deps = ['build:deno', 'build:go', 'build:racket']
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3 -N\
    './deno/build/compile ./ff/example.ff'\
    './go/build/compile --in ./ff/example.ff'\
    './racket/main.rkt -c ./ff/example.ff'
'''

[[task]]
name = 'loc'
deps = ['clean']
validation = 'none'
run = 'cloc --force-lang-def=.cloc . --quiet --md --hide-rate > loc.md'
