version = 0.1
default-task = 'build:'

[[task]]
name = 'build:#'
dep = '#/chompfile.toml'
validation = 'none'
run = 'chomp -c $DEP build'

[[task]]
name = 'test:#'
dep = '#/chompfile.toml'
serial = true
display = 'init-only'
run = '''
  chomp -c $DEP test
  echo ""
  echo ""
'''

[[task]]
name = 'clean:#'
dep = '#/chompfile.toml'
validation = 'none'
run = 'chomp -c $DEP clean'

[[task]]
name = 'interpret:#'
dep = '#/chompfile.toml'
validation = 'none'
serial = true
run = '''
  chomp -c $DEP interpret
  echo ""
  echo ""
'''

[[task]]
name = 'execute:#'
dep = '#/chompfile.toml'
validation = 'none'
serial = true
run = '''
  chomp -c $DEP execute
  echo ""
  echo ""
'''
