version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[env]
BLUE = '\033[0;34m'
NC = '\033[0m'
BIN = './bin/dart.exe'
PP = '../deno/build/compile --opt --disassemble'
CHECK = 'printf "  ${GRN}OK${NC} " || printf "  ${RED}FAIL${NC} "'
RED = '\033[0;31m'
GRN = '\033[0;32m'

[[task]]
target = './bin/#.exe'
deps = ['./bin/#.dart']
run = '''
  dart compile exe $DEP
'''

[[task]]
name = 'build'
deps = ['./bin/dart.exe']

[[task]]
name = 'interpret'
dep = './bin/dart.exe'
run = 'cat ../ff/example_v0.ff | ./bin/dart.exe'
template = 'cmp'
[task.template-options]
cmp = '../ff/example_v0.out'

[[task]]
display = 'none'
name = 'build-deno-compiler'
run = 'chomp -c ../deno/ :disassemble'

[[task]]
name = 'test'
deps = [
    ':build',
    ':interpret',
]
serial = true
display = 'none'

[[task]]
name = 'ff'
deps = [
 '../build/disassemble/##.ff',
  'build-deno-compiler',
  './bin/dart.exe',
]
target = '../ff/##.out'
serial = true
invalidation = 'always'
validation = 'none'
display = 'status-only'
run = '''
  cat $DEP | ${{BIN}}
'''
template = 'cmp'
[task.template-options]
cmp = '$TARGET'

[[task]]
name = 'clean'
run = '''
  rm -./bin/dart.exe
'''
