version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[env]
NC = '\033[0m'
BLUE = '\033[0;34m'
CHECK = 'printf "  ${GRN}OK${NC} " || printf "  ${RED}FAIL${NC} "'
RED = '\033[0;31m'
GRN = '\033[0;32m'

[[task]]
target = './build/#'
deps = ['./#.rkt', './**/*.rkt']
run = '''
  raco exe --gui -o $TARGET $DEP
'''

[[task]]
name = 'build'
deps = ['./build/example']

[[task]]
name = 'interpret'
deps = ['./build/example']
run = './build/example'
template = 'cmp'
[task.template-options]
cmp = '../ff/example_v0.out'

[[task]]
name = 'test'
deps = [':interpret']
serial = true
display = 'none'

[[task]]
display = 'none'
name = 'build-deno-compiler'
run = 'chomp -c ../deno/ :disassemble'

[[task]]
name = 'ff'
deps = [
  '../build/disassemble/##.ff',
  'build-deno-compiler',
]
target = '../ff/##.out'
serial = true
invalidation = 'always'
validation = 'none'
display = 'status-only'
run = '''
  racket ./ff.rkt $DEP
'''
template = 'cmp'
[task.template-options]
cmp = '$TARGET'

[[task]]
name = 'clean'
run = '''
  rm -rf ./build
'''
