version = 0.1
default-task = 'build'

[env]
GPP_U = '"#" "" "(" "," ")" "(" ")" "#" ""'
GPP_M = '"#" "\n" " " " " "\n" "(" ")"'
GPP_S = '"\"" "\"" ";;"'

[[task]]
name = 'example'
deps = ['execute:example']

[[task]]
name = 'run:#'
dep = './#.wat'
run = '''
cat $DEP | eval gpp -U ${GPP_U} -M ${GPP_M} | wasmtime -
'''

[[task]]
name = 'build'
deps = ['build/example.wasm', 'build/interpret.wasm']

[[task]]
name = 'gpp'
target = 'build/##.wat'
dep = '##.wat'
run = '''
  cat $DEP | eval gpp -U ${GPP_U} -M ${GPP_M} +s ${GPP_S} > $TARGET
'''

[[task]]
name = 'wat2wasm'
target = 'build/##.wasm'
dep = 'build/##.wat'
run = '''
  wat2wasm $DEP -o $TARGET
'''

[[task]]
name = 'wat2wasm:example'
target = 'build/example.wasm'
dep = 'build/example.wat'
run = '''
  wat2wasm $DEP -o $TARGET
'''

[[task]]
name = 'wat2wasm:interpret'
target = 'build/interpret.wasm'
dep = 'build/interpret.wat'
run = '''
  wat2wasm $DEP -o $TARGET
'''

[[task]]
name = 'execute'
deps = ['execute:example']

[[task]]
name = 'execute:example'
deps = ['build/example.wasm']
run = 'wasmtime $DEP'

[[task]]
name = 'execute:interpret'
deps = ['build/interpret.wasm']
run = 'node --experimental-modules --experimental-wasm-modules ./interpret.js'

