version = 0.1
default-task = 'build'

[[task]]
name = 'example'
deps = ['interpret:example']

[[task]]
name = 'interpret'
deps = [
  'build:interpret'
]
run = '''
  node --experimental-modules --experimental-wasm-modules ./interpret.js
'''

[[task]]
name = 'interpret:#'
dep = './#.wat'
run = 'wasmtime $DEP'

[[task]]
name = 'build'
deps = ['build:example']

[[task]]
name = 'build:#'
target = './build/#.wasm'
deps = ['./#.wat']
run = '''
  wat2wasm $DEP -o $TARGET
'''

[[task]]
name = 'execute'
deps = ['execute:example']

[[task]]
name = 'execute:#'
dep = './build/#.wasm'
run = 'wasmtime $DEP'

