[package]
name = "f-flat-minor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num = "0.4"

[[bin]]
name = "example0"
path = "example0.rs"