version = 0.1
default-task = 'test'

extensions = ['../cmp-extension.js']

[env]
RED = '\033[0;31m'
CHECK = 'printf "  ${GRN}OK${NC} " || printf "  ${RED}FAIL${NC} "'
BLUE = '\033[0;34m'
NC = '\033[0m'
GRN = '\033[0;32m'
BIN = 'node --experimental-transform-types --disable-warning=ExperimentalWarning ./bin/ff-run.ts'

[[task]]
name = 'test:interpret'
dep = './bin/ff-run.ts'
template = 'cmp'
run = '$BIN ../ff/example.ff'
[task.template-options]
cmp = '../ff/example.out'

[[task]]
name = 'test:ffp'
dep = './bin/ff-run.ts'
template = 'cmp'
run = '$BIN ../ff/hello.ffp'
[task.template-options]
cmp = '../ff/hello.out'

[[task]]
name = 'test:out'
deps = [
  '../ff/##.out',
  './bin/ff-run.ts'
]
serial = true
invalidation = 'always'
validation = 'none'
display = 'status-only'
run = '''
  shopt -s nullglob
  shopt -s extglob
  for i in "${DEP%.*}.ff?(p)"; do
    $BIN $i | cmp - $DEP -s && ${{CHECK}};
    $BIN $i --opt | cmp - $DEP -s && ${{CHECK}};
  done
'''

[[task]]
name = 'test:tap'
deps = [
  './bin/ff-run.ts'
]
serial = true
invalidation = 'always'
validation = 'none'
run = '''
  shopt -s nullglob
  shopt -s extglob
  shopt -s globstar
  prove --exec "$BIN --opt" ../ff/**/*.test.ffp
'''

[[task]]
name = 'test'
deps = [
  ':test:interpret',
  ':test:ffp',
  ':test:out',
  ':test:tap'
]
serial = true
display = 'none'

[[task]]
name = 'bench'
deps = ['build:run']
validation = 'none'
serial = true
run = '''
  hyperfine --warmup 3 -N \
    '$BIN ../ff/example.ff'\
    '$BIN ../ff/example.ff --opt'
'''
