default-task = 'build'
version = 0.1

[env]
RED = "\\033[0;31m"
NC = "\\033[0m"
GRN = "\\033[0;32m"
BLUE = "\\033[0;34m"
CHECK = "printf \"${GRN}OK${NC} \" || printf \"${RED}FAIL${NC} \""

[[task]]
target = './build/##'
deps = ['./cmd/##', './cmd/**/*.go', './src/**/*.go']
run = '''
  go build -o $TARGET $DEP
'''

[[task]]
deps = ['./build/compile', './build/execute', './build/run', './build/repl']
name = 'build'

[[task]]
name = 'clean'
run = '''
  rm -rf ./build
'''

[[task]]
dep = './build/compile'
name = 'go-compile'
run = '''
	./build/compile --in ../ff/example.ff | cmp --s - "../ff/example.ffb"
'''

[[task]]
dep = './build/execute'
name = 'go-execute'
run = '''
	cat ../ff/example.ffb | ./build/execute | cmp --s - "../ff/example.out"
'''

[[task]]
dep = './build/run'
name = 'go-interpret'
run = '''
	./build/run --in ../ff/example.ff | cmp --s - "../ff/example.out"
'''

[[task]]
deps = ['build', ':go-compile', ':go-execute', ':go-interpret', ':go-ff']
display = 'none'
name = 'test'
serial = true

[[task]]
deps = ['../ff/##.out', './build/run']
display = 'status-only'
invalidation = "always"
name = 'go-ff'
run = '''
  shopt -s nullglob
  shopt -s extglob
  for i in "${DEP%.*}.ff?(p)"; do
    ./build/run --in $i | cmp - $DEP -s && ${{CHECK}};
  done
'''
serial = true
validation = "none"
