version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[env]
RED = '\033[0;31m'
BLUE = '\033[0;34m'
BIN = './execute.py'
NC = '\033[0m'
GRN = '\033[0;32m'
CHECK = 'printf "  ${GRN}OK${NC} " || printf "  ${RED}FAIL${NC} "'

[[task]]
display = 'none'
name = 'build-go-precompiler'
run = 'chomp -c ../go/ build:preprocess'

[[task]]
display = 'none'
name = 'build-deno-preprocessor'
run = 'chomp -c ../deno/ build:preprocess'

[[task]]
name = 'interpret'
run = 'cat ../ff/example.ff | ${{BIN}}'
template = 'cmp'
[task.template-options]
cmp = '../ff/example.out'

[[task]]
name = 'test'
deps = [
  ':interpret',
  ':ff',
  ':test:tap'
]
serial = true
display = 'none'

[[task]]
name = 'test:tap'
deps = [
    'build-go-precompiler',
    'build-deno-preprocessor',
]
serial = true
invalidation = 'always'
validation = 'none'
run = '''
  shopt -s nullglob
  shopt -s extglob
  shopt -s globstar
  prove --exec '../shell/ff-run.sh' ../ff/**/*.test.ffp
'''

[[task]]
name = 'ff'
deps = [
    '../ff/##.out',
    'build-go-precompiler',
    'build-deno-preprocessor',
]
serial = true
invalidation = 'always'
validation = 'none'
display = 'status-only'
run = '''
  if [ -f ${DEP%.*}.ffp ]; then
    ../shell/ff-run.sh ${DEP%.*}.ffp | cmp - $DEP -s && ${{CHECK}};
  fi
  if [ -f ${DEP%.*}.ff ]; then
    cat ${DEP%.*}.ff | ${{BIN}} | cmp - $DEP -s && ${{CHECK}};
  fi
'''
