version = 0.1
default-task = 'build'

extensions = ['../cmp-extension.js']

[env]
RED = '\033[0;31m'
BLUE = '\033[0;34m'
BIN = './execute.py'
NC = '\033[0m'
GRN = '\033[0;32m'
CHECK = 'printf "  ${GRN}OK${NC} " || printf "  ${RED}FAIL${NC} "'

[[task]]
name = 'build-deno-preprocess'
run = 'chomp -c ../deno/ build'

[[task]]
name = 'interpret'
run = 'cat ../ff/example.ff | ${{BIN}}'
template = 'cmp'
[task.template-options]
cmp = '../ff/example.out'

[[task]]
name = 'test'
deps = [
  ':interpret',
  ':ff',
]
serial = true
display = 'none'

[[task]]
name = 'ff'
deps = [
    '../ff/##.out',
    '../deno/build/preprocess',
]
serial = true
invalidation = 'always'
validation = 'none'
display = 'status-only'
run = '''
  if [ -f ${DEP%.*}.ffp ]; then
    ../deno/build/preprocess ${DEP%.*}.ffp | ${{BIN}} | cmp - $DEP -s && ${{CHECK}};
  fi
  if [ -f ${DEP%.*}.ff ]; then
    cat ${DEP%.*}.ff | ${{BIN}} | cmp - $DEP -s && ${{CHECK}};
  fi
'''
